### ISSUE TITLE
下拉刷新不弹回

### ISSUE THREAD

**Issue by xubenliang** [Aspsine/SwipeToLoadLayout#57]
最近遇到一个问题，初次进入首页，先自动刷新，在刷新过程中，瞬间切换到其他Fragment页面，然后返回到开始的页面，发现下拉刷新不弹回，每次都能测试出来。

后面突然还出现一次奔溃：
Device: Xiaomi HM NOTE 1LTE 
Stack trace:  
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558426, class android.widget.ListView) with Adapter(class com.dsdyf.seller.ui.fragment.MyStoreFragment$4)]
	at android.widget.ListView.layoutChildren(ListView.java:1555)
	at android.widget.AbsListView.onLayout(AbsListView.java:2089)
	at android.view.View.layout(View.java:14828)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.layoutChildren(SwipeToLoadLayout.java:846)
	at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.updateScroll(SwipeToLoadLayout.java:1259)
	at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.access$1600(SwipeToLoadLayout.java:28)
	at com.aspsine.swipetoloadlayout.SwipeToLoadLayout$AutoScroller.run(SwipeToLoadLayout.java:1340)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5052)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Aspsine** [comment]
崩溃问题是更新了数据源之后没有调用`notifyDataSetChanged()`。比如如下使用方式就可能出现崩溃。
```java
onSuccess(data){
  mList.addAll(data);
  swipeToLoadLayout.setRefreshing(false);
  mAdapter.notifyDataSetChanged();
}
```
按照上面这样的用法，就会出现如上崩溃。
请修改为：
```java
onSuccess(data){
  swipeToLoadLayout.setRefreshing(false);
  mList.addAll(data);
  mAdapter.notifyDataSetChanged();
}
```

不弹回问题:
1.开启log
```java
swipeLoadLayout.setDebug(true);
```
2.重复操作
3.用`SwipeToLoadLayout`作为log filter, 提供一下logcat中的log信息。
4.最好能提供切换fragment的方式，结合fragment生命周期更好分析。

**Comment by xubenliang** [comment]
给你点个赞，这么快就给回复了！
1.奔溃问题也就遇到这么一次，我看了下我的代码，是跟你的给的方案一样的。先停止下拉刷新，再加载数据，然后刷新的。

2.我把这个切换的问题录制成视频了，已上传到优酷。
http://v.youku.com/v_show/id_XMTU2MDI2NTUwOA==.html

日志打印正常的流程是这样的：
05-06 13:25:59.982 5187-5187/com.dsdyf.seller D/SwipeToLoadLayout: printStatus:status_refreshing
05-06 13:26:02.603 5187-5187/com.dsdyf.seller D/SwipeToLoadLayout: printStatus:stats_refresh_complete
05-06 13:26:03.034 5187-5187/com.dsdyf.seller D/SwipeToLoadLayout: printStatus:status_default
出问题的是这样的：
05-06 13:25:48.939 5187-5187/com.dsdyf.seller D/SwipeToLoadLayout: printStatus:status_refreshing
05-06 13:25:49.534 5187-5187/com.dsdyf.seller D/SwipeToLoadLayout: printStatus:stats_refresh_complete

**Comment by Aspsine** [comment]
在V 1.0.3中log的level都调整成了i，V 1.0.3之前是d。
看log貌似你用的不是最新版本（v 1.0.3）？

**Comment by xubenliang** [comment]
之前是用了v1.0.3，但是有个快速切换，导致不刷新的问题，所以后面回到了v1.0.2

**Comment by Aspsine** [comment]
v1.0.2中不回弹的问题在v1.0.3中已经修复了。
详见：https://github.com/Aspsine/SwipeToLoadLayout/releases/tag/1.0.3

v1.0.3快速切换不刷新是什么问题？

**Comment by xubenliang** [comment]
那我晚点换到v1.0.3，然后再录制视频给你看下。

**Comment by Aspsine** [comment]
@xubenliang 有劳。

**Comment by xubenliang** [comment]
已经切换到v1.0.3，那个不弹回的问题的确修复好了。

之前用v1.0.3遇到的问题，已经录制了视频：
http://v.youku.com/v_show/id_XMTU2MDM4MDUyMA==.html
开始是点击奖励，然后还在刷新过程中，快速切换到价格，然后就不执行价格的刷新。
