### ISSUE TITLE
好像不能嵌套CoordinatorLayout

### ISSUE THREAD

**Issue by damingwangguan** [Aspsine/SwipeToLoadLayout#69]
```xml
<com.aspsine.swipetoloadlayout.SwipeToLoadLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/pl"
    android:layout_height="match_parent">

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <LinearLayout
                android:id="@+id/toolsssssbar"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:background="#FFFFFF"
                android:gravity="center_vertical"
                android:orientation="vertical"
                app:layout_scrollFlags="scroll"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light">

                <Button
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="点我" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="the best app" />
            </LinearLayout>

            <android.support.design.widget.TabLayout
                android:id="@+id/tabs"
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:background="#810e88" />

        </android.support.design.widget.AppBarLayout>

        <android.support.v4.view.ViewPager
            android:id="@+id/vp_body"
            android:layout_width="match_parent"
            android:layout_height="800dp"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            >

        </android.support.v4.view.ViewPager>

    </android.support.design.widget.CoordinatorLayout>
</com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
```

下拉报错
>>
  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
                                                                             at android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:35)
                                                                             at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:1274)
                                                                             at android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1737)
                                                                             at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.canChildScrollUp(SwipeToLoadLayout.java:976)
                                                                             at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onCheckCanRefresh(SwipeToLoadLayout.java:1374)
                                                                             at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onTouchEvent(SwipeToLoadLayout.java:556)
                                                                             at android.view.View.dispatchTouchEvent(View.java:9294)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                             at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.dispatchTouchEvent(SwipeToLoadLayout.java:453)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                             at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                             at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                             at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                             at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
                                                                             at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
                                                                         	at android.view.Ch

**Comment by Aspsine** [comment]
ids are error,
please check out. #45

**Comment by Aspsine** [comment]
close for no responding.
