### ISSUE TITLE
报错boolean android.view.View.canScrollVertically(int)' on a null object reference请求帮忙

### ISSUE THREAD

**Issue by SawCao** [Aspsine/SwipeToLoadLayout#80]
代码是按照demo里面的GoogleStyleFragment写的，activity布局是这个
```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                 xmlns:app="http://schemas.android.com/apk/res-auto"
                                                 android:id="@+id/myCoordinator"
                                                 android:layout_width="match_parent"
                                                 android:layout_height="match_parent"
                                                 android:fitsSystemWindows="true">
    <android.support.design.widget.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:elevation="0dp">
        <FrameLayout
            android:id="@+id/toolbar_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:elevation="0dp"
            app:theme="@style/MyToolbarTheme"
            app:popupTheme="@style/ToolbarPopupTheme"
            app:contentInsetStart="0dp"
            app:layout_scrollFlags="scroll|enterAlways">
            <ImageView
                android:id="@+id/content_hamburger"
                style="@style/ImageView.Hamburger"
                android:src="@drawable/ic_add_blue"
                android:clickable="true"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="#212121"
                android:text="易书"
                android:layout_gravity="center"
                android:textSize="@dimen/guillotine_item_text_size"/>
        </android.support.v7.widget.Toolbar>

        </FrameLayout>
    </android.support.design.widget.AppBarLayout>
    <FrameLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        android:fillViewport="true"/>
    <android.support.v4.widget.NestedScrollView
        android:id="@+id/myScrollingContent"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fillViewport="true">
    </android.support.v4.widget.NestedScrollView>
</android.support.design.widget.CoordinatorLayout>
```

这是fragment的布局

   ```
<com.aspsine.swipetoloadlayout.SwipeToLoadLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                 xmlns:app="http://schemas.android.com/apk/res-auto"
                                                 android:id="@+id/swipeToLoadLayout"
                                                 android:layout_width="match_parent"
                                                 android:layout_height="match_parent"
                                                 android:background="#212121"
                                                 app:default_to_loading_more_scrolling_duration="500"
                                                 app:load_more_final_drag_offset="@dimen/load_more_final_offset_google"
                                                 app:load_more_trigger_offset="@dimen/load_more_trigger_offset_google"
                                                 app:refresh_final_drag_offset="@dimen/refresh_final_offset_google"
                                                 app:refresh_trigger_offset="@dimen/refresh_trigger_offset_google"
                                                 app:load_more_complete_delay_duration="0"
                                                 app:swipe_style="above">

    <include
        android:id="@id/swipe_refresh_header"
        layout="@layout/refresh_header" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_note"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"
        android:clipToPadding="false"/>

    <include
        android:id="@id/swipe_load_more_footer"
        layout="@layout/refresh_footer" />

</com.aspsine.swipetoloadlayout.SwipeToLoadLayout>
```
报错为
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
                                                                   at android.support.v4.view.ViewCompatICS.canScrollVertically(ViewCompatICS.java:35)
                                                                   at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollVertically(ViewCompat.java:1274)
                                                                   at android.support.v4.view.ViewCompat.canScrollVertically(ViewCompat.java:1737)
                                                                   at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.canChildScrollUp(SwipeToLoadLayout.java:976)
                                                                   at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onCheckCanRefresh(SwipeToLoadLayout.java:1374)
                                                                   at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.onTouchEvent(SwipeToLoadLayout.java:556)
                                                                   at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                   at com.aspsine.swipetoloadlayout.SwipeToLoadLayout.dispatchTouchEvent(SwipeToLoadLayout.java:453)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                   at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                               	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java
```

初学Android开发，问题可能很简单，请海涵，但以我目前水平无法解决，望能帮忙看看，谢谢~

**Comment by Aspsine** [comment]
#49

**Comment by SawCao** [comment]
thanks

**Comment by dashuyadashu** [comment]
谢谢！@Aspsine
